services:
  ml-service:
    build:
      context: ./ml-service
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - monitoring
    labels:
      - "monitoring=true"
      - "service=ml-service"

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    restart: unless-stopped
    init: true
    env_file: ./.env
    networks:
      - monitoring
    labels:
      - "monitoring=true"
      - "service=server"

  client:
    build:
      context: ./client
    ports:
      - "80:80"
    restart: unless-stopped
    init: true
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring

volumes:
  grafana-data:

networks:
  monitoring:
    driver: bridge
