global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "server"
    static_configs:
      - targets: ["server:5000"]

  - job_name: "ml-service"
    static_configs:
      - targets: ["ml-service:8000"]
